version: '3.8'

services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: docc_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: docc_erp
      MYSQL_USER: docc_user
      MYSQL_PASSWORD: docc_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - docc_network
    restart: unless-stopped

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: docc_backend
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: docc_erp
      DB_USER: docc_user
      DB_PASSWORD: docc_pass
      JWT_SECRET: your_jwt_secret_key_here
      PORT: 5000
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    networks:
      - docc_network
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: docc_frontend
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - docc_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped


volumes:
  mysql_data:

networks:
  docc_network:
    driver: bridge
